#!/bin/bash

# Config
PROJECT=paranoia
ZIPALIGN=$HOME/.android/android-sdk-linux/build-tools/23.0.3/zipalign
KEYSTORE=../../../myks.keystore
ENABLE_PAK="false" # "true"

if [[ "$1" = "--help" ]]; then
	echo "Usage: ./build.sh <release|debug> <gp|nongp>"
	exit 0
fi

if [[ "$#" -ne "2" ]]; then
	echo "Illegal number of parameters, see ./build.sh --help"
	exit 0
fi

if [[ "$1" = "release" ]]; then
	VERBOSE="0 APP_CFLAGS=\"-w\""
	RELEASE="0"
	GEN_CONFIG="release"
else
	RELEASE="1 APP_CFLAGS=\"-gdwarf-3\""
	GEN_CONFIG=""
fi

if [[ "$2" = "gp" ]]; then
	GP="1"
	NAME_POSTFIX="gp"
	GEN_CONFIG_GP="gp"
else
	GP="0"
	NAME_POSTFIX="nongp"
	GEN_CONFIG_GP=""
fi

echo "*****************************************"
echo "* GP: $GP "
echo "* RELEASETYPE: $RELEASE "
echo "*****************************************"

set -x

# Regenerate PAK file
if [[ "$ENABLE_PAK" -ne "true" ]]; then
	mkdir -p pak/
	mkdir -p assets/
	python2 makepak.py pak/ assets/extras.pak
fi

./gen-config.sh $GEN_CONFIG $GEN_CONFIG_GP 
./gen-version.sh

# Build
ndk-build -j8 NDK_TOOLCHAIN_VERSION=4.8 NDK_DEBUG=$RELEASE V=$VERBOSE GOOGLE_PLAY_BUILD=$GP
ant $1

if [[ "$1" = "release" ]]; then
	jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore ${KEYSTORE} bin/${PROJECT}-$1-unsigned.apk xashdroid
	${ZIPALIGN} 4 bin/${PROJECT}-$1-unsigned.apk bin/${PROJECT}.apk
fi
mv bin/${PROJECT}.apk ${PROJECT}-$1-$NAME_POSTFIX.apk

